export const projectData = [
  {
    image: "/assets/work/3.png",
    category: "react js",
    name: "Nexa Website",
    description: "project description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/4.png",
    category: "react js",
    name: "Nexa Website",
    description: "project description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/3.png",
    category: "next js",
    name: "Nexa Website",
    description: "project description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/4.png",
    category: "next js",
    name: "Nexa Website",
    description: "project description",
    link: "/",
    github: "/",
  },
  {
    image: "/assets/work/3.png",
    category: "full stack",
    name: "Nexa Website",
    description: "project description",
    link: "/",
    github: "/",
  },
];
